import type { TResume } from "@/lib/types"

export const mockResume: TResume = {
  skills: [
    { isShow: true, name: "Javascript" },
    { isShow: true, name: "Typescript" },
    { isShow: true, name: "Frontend & Backend Web Development" },
    { isShow: true, name: "React.js" },
    { isShow: true, name: "Zustand state library" },
  ],
  title: "Computer Engineer",
  firstName: "Burakhan",
  lastName: "Unverunver",
  email: "burakhanunver@gmail.com",
  tel: "9555 555 55 55",
  about:
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur ratione, eligendi consequuntur sequi quas consectetur ipsam? Dolor vitae odio ad.",
  educations: [
    {
      isShow: true,
      city: "London",
      degree: "Bachelor's Degree",
      endMonth: "June",
      endYear: "2025",
      schoolName: "New york state university",
      startMonth: "July",
      startYear: "2021",
    },
    {
      isShow: true,
      city: "London",
      degree: "Bachelor's Degree",
      endMonth: "June",
      endYear: "2025",
      schoolName: "New york state university",
      startMonth: "July",
      startYear: "2021",
    },
    {
      isShow: true,
      city: "London",
      degree: "Bachelor's Degree",
      endMonth: "June",
      endYear: "2025",
      schoolName: "New york state university",
      startMonth: "July",
      startYear: "2021",
    },
  ],
  jobs: [
    {
      isShow: true,
      city: "New york",
      company: "Acme company",
      endMonth: "December",
      endYear: "2026",
      startMonth: "January",
      startYear: "2026",
      title: "Frontend developer intern",
    },
    {
      isShow: true,
      city: "New york",
      company: "Acme company",
      endMonth: "December",
      endYear: "2026",
      startMonth: "January",
      startYear: "2026",
      title: "Backend Web Developer",
    },
    {
      isShow: true,
      city: "New york",
      company: "Acme company",
      endMonth: "December",
      endYear: "2026",
      startMonth: "January",
      startYear: "2026",
      title: "Backend Web Developer",
    },
  ],
  languages: [
    { isShow: true, language: "English", level: "B1" },
    { isShow: true, language: "Spanish", level: "A2" },
    { isShow: true, language: "German", level: "A1" },
  ],
}
